package com.marine.ViteLaRecette.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;


import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.DaoConfig;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.IdentityScopeType;
import com.marine.ViteLaRecette.dao.Categorie;
import com.marine.ViteLaRecette.dao.CategorieDao;
import com.marine.ViteLaRecette.dao.Ingredient;
import com.marine.ViteLaRecette.dao.IngredientDao;
import com.marine.ViteLaRecette.dao.Liste;
import com.marine.ViteLaRecette.dao.ListeDao;
import com.marine.ViteLaRecette.dao.Mesure;
import com.marine.ViteLaRecette.dao.MesureDao;
import com.marine.ViteLaRecette.dao.Quantite;
import com.marine.ViteLaRecette.dao.QuantiteDao;
import com.marine.ViteLaRecette.dao.Recette;
import com.marine.ViteLaRecette.dao.RecetteDao;
import com.marine.ViteLaRecette.dao.Ur;
import com.marine.ViteLaRecette.dao.UrDao;
import com.marine.ViteLaRecette.dao.Ustensile;
import com.marine.ViteLaRecette.dao.UstensileDao;
import com.marine.ViteLaRecette.dao.Vocabulaire;
import com.marine.ViteLaRecette.dao.VocabulaireDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

	private final DaoConfig ingredientDaoConfig;
	private final DaoConfig categorieDaoConfig;
	private final DaoConfig ustensileDaoConfig;
	private final DaoConfig mesureDaoConfig;
	private final DaoConfig recetteDaoConfig;
	private final DaoConfig quantiteDaoConfig;
	private final DaoConfig listeDaoConfig;
	private final DaoConfig urDaoConfig;
	private final DaoConfig vocabulaireDaoConfig;

	private final IngredientDao ingredientDao;
	private final CategorieDao categorieDao;
	private final UstensileDao ustensileDao;
	private final MesureDao mesureDao;
	private final RecetteDao recetteDao;
	private final QuantiteDao quantiteDao;
	private final ListeDao listeDao;
	private final UrDao urDao;
	private final VocabulaireDao vocabulaireDao;

	public DaoSession(SQLiteDatabase db, IdentityScopeType type,
			Map<Class<? extends AbstractDao<?, ?>>, DaoConfig> daoConfigMap) {
		super(db);

		ingredientDaoConfig = daoConfigMap.get(IngredientDao.class).clone();
		ingredientDaoConfig.initIdentityScope(type);

		categorieDaoConfig = daoConfigMap.get(CategorieDao.class).clone();
		categorieDaoConfig.initIdentityScope(type);

		ustensileDaoConfig = daoConfigMap.get(UstensileDao.class).clone();
		ustensileDaoConfig.initIdentityScope(type);

		mesureDaoConfig = daoConfigMap.get(MesureDao.class).clone();
		mesureDaoConfig.initIdentityScope(type);

		recetteDaoConfig = daoConfigMap.get(RecetteDao.class).clone();
		recetteDaoConfig.initIdentityScope(type);

		quantiteDaoConfig = daoConfigMap.get(QuantiteDao.class).clone();
		quantiteDaoConfig.initIdentityScope(type);

		listeDaoConfig = daoConfigMap.get(ListeDao.class).clone();
		listeDaoConfig.initIdentityScope(type);

		urDaoConfig = daoConfigMap.get(UrDao.class).clone();
		urDaoConfig.initIdentityScope(type);

		vocabulaireDaoConfig = daoConfigMap.get(VocabulaireDao.class).clone();
		vocabulaireDaoConfig.initIdentityScope(type);

		ingredientDao = new IngredientDao(ingredientDaoConfig, this);
		categorieDao = new CategorieDao(categorieDaoConfig, this);
		ustensileDao = new UstensileDao(ustensileDaoConfig, this);
		mesureDao = new MesureDao(mesureDaoConfig, this);
		recetteDao = new RecetteDao(recetteDaoConfig, this);
		quantiteDao = new QuantiteDao(quantiteDaoConfig, this);
		listeDao = new ListeDao(listeDaoConfig, this);
		urDao = new UrDao(urDaoConfig, this);
		vocabulaireDao = new VocabulaireDao(vocabulaireDaoConfig, this);

		registerDao(Ingredient.class, ingredientDao);
		registerDao(Categorie.class, categorieDao);
		registerDao(Ustensile.class, ustensileDao);
		registerDao(Mesure.class, mesureDao);
		registerDao(Recette.class, recetteDao);
		registerDao(Quantite.class, quantiteDao);
		registerDao(Liste.class, listeDao);
		registerDao(Ur.class, urDao);
		registerDao(Vocabulaire.class, vocabulaireDao);
	}

	public void clear() {
		ingredientDaoConfig.getIdentityScope().clear();
		categorieDaoConfig.getIdentityScope().clear();
		ustensileDaoConfig.getIdentityScope().clear();
		mesureDaoConfig.getIdentityScope().clear();
		recetteDaoConfig.getIdentityScope().clear();
		quantiteDaoConfig.getIdentityScope().clear();
		listeDaoConfig.getIdentityScope().clear();
		urDaoConfig.getIdentityScope().clear();
		vocabulaireDaoConfig.getIdentityScope().clear();
	}

	public IngredientDao getIngredientDao() {
		return ingredientDao;
	}

	public CategorieDao getCategorieDao() {
		return categorieDao;
	}

	public UstensileDao getUstensileDao() {
		return ustensileDao;
	}

	public MesureDao getMesureDao() {
		return mesureDao;
	}

	public RecetteDao getRecetteDao() {
		return recetteDao;
	}

	public QuantiteDao getQuantiteDao() {
		return quantiteDao;
	}

	public ListeDao getListeDao() {
		return listeDao;
	}

	public UrDao getUrDao() {
		return urDao;
	}

	public VocabulaireDao getVocabulaireDao() {
		return vocabulaireDao;
	}

}
