package com.marine.ViteLaRecette.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table MESURE.
 */
public class Mesure {

	private Long id;
	private String nom;

	public Mesure() {
	}

	public Mesure(Long id) {
		this.id = id;
	}

	public Mesure(Long id, String nom) {
		this.id = id;
		this.nom = nom;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getNom() {
		return nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

}
