package com.marine.ViteLaRecette.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table USTENSILE.
 */
public class Ustensile {

	private Long id;
	private String nom;

	public Ustensile() {
	}

	public Ustensile(Long id) {
		this.id = id;
	}

	public Ustensile(Long id, String nom) {
		this.id = id;
		this.nom = nom;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getNom() {
		return nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

}
